name: Release
on:
    push:
        branches:
            - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
    release:
        # IMPORTANT: prevent this action from running on forks
        if: github.repository == 'lemoncloud-io/lemon-front-lib'
        permissions:
            contents: write
            pull-requests: write
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: pnpm/action-setup@v2
              with:
                  version: 6.0.2
            - run: pnpm i
            - name: Publish to pnpm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
